### ISSUE TITLE
Tag 1.0.0

### ISSUE THREAD

**Issue by davidanthoff** [timholy/FlameGraphs.jl#19]
Could we just tag 1.0.0 and follow semver? For example, the recent v0.2.0 seems not breaking, but actually required bounds updates in all depending packages. Seems less likely to happen once we are past 1.0.0 :)

**Comment by timholy** [comment]
It depends on what you mean by breaking. The fields of FlameColors changed, as did the output people see (the color scheme is quite different from what it used to be). I think these are both pretty minor, but it seemed best to bump the minor version especially because of the field change.

Support for #7 seems in principle like it might benefit from further changes to the API. Once that lands then maybe we should go to 1.0.
